import Head from 'next/head'
import { useState, useMemo } from 'react'
import MaterialReactTable from 'material-react-table';
import type { MRT_ColumnDef } from 'material-react-table';
//Components
import { TableSelector } from '@/components/TableSelector'
//Icons
import {IoNewspaperSharp} from 'react-icons/io5'
import {AiFillCar} from 'react-icons/ai'
import {MdBadge} from 'react-icons/md'
import {FaUser} from 'react-icons/fa'

interface HomeProps {
  data: any
}
export default function Home({
  data
}: HomeProps) {
  const [tables, setTables] = useState([
    {
      name: 'infracciones',
      icon: <IoNewspaperSharp color='#4b5563' size={20}/>,
      selected: true
    },
    {
      name: 'vehiculos',
      icon: <AiFillCar color='#4b5563' size={20}/>,
      selected: false
    },
    {
      name: 'matriculas',
      icon: <MdBadge color='#4b5563' size={20}/>,
      selected: false
    },
    {
      name: 'propietarios',
      icon: <FaUser color='#4b5563' size={20}/>,
      selected: false
    }
  ])

  const [tableData, setTableData] = useState(data)

  const columns = useMemo(
    () => {
      const firstRow = tableData[0]
      const columns: MRT_ColumnDef[] = []
      for (const key in firstRow) {
        columns.push({
          accessorKey: key,
          header: key,
        })
      }
      return columns
    },
    [tableData]
  );

  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-5'>
        <h1 className="text-2xl font-bold text-center text-gray-600">Selecciona una tabla</h1>
        <div className="tableButtons flex flex-wrap justify-center">
          {
            tables.map((table) => (
              <TableSelector
                key={table.name}
                title={table.name}
                icon={table.icon}
                onClick={() => console.log(table.name)} 
                selected={table.selected}
              />
            ))
          }
        </div>
        <div className="table w-full overflow-x-scroll">
          <MaterialReactTable
            columns={columns}
            data={tableData}
            muiTableContainerProps={{
              sx: { maxHeight: '600px', maxWidth: '90vw' }, //give the table a max height
            }}
          />
        </div>
      </main>
    </>
  )
}

//Get server side props
export async function getServerSideProps() {
  try {
    const url = 'https://crud-transito-backend.vercel.app'
    const res = await fetch(`${url}/api/infraccion`)
    const data = await res.json()
    return {
      props: {
        data
      }
    }
  } catch (error) {
    console.log(error)
    return{
      props: {
        data: []
      }
    }
  }
}
